### ISSUE TITLE
Error when adding buildModules to nuxt.config with NaiveUI

### ISSUE THREAD

**Issue by Naybnet** [Baiyuetribe/nuxt3-naive-ui-starter#8]
Hello ! Thanks for the great work. Using your module alone works fine but I am having a hard time integrating it to my project that uses modules ([supabase integration](https://github.com/larbish/supabase-module)).

## Environment

```
Nuxt CLI v3.0.0-27409835.c53c736                                                                             11:57:10
RootDir: /media/workspace/code/nuxt3-naive-ui-starter                                       11:57:11
Nuxt project info:                                                                                           11:57:11

------------------------------
- Operating System: `Linux`
- Node Version:     `v17.3.0`
- Nuxt Version:     `3.0.0-27409835.c53c736`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `build`, `vite`, `buildModules`, `supabase`
- Runtime Modules:  `-`
- Build Modules:    `@larbish/supabase@0.0.13`
------------------------------
```

## Reproduction

https://stackblitz.com/edit/github-9zcuqu?file=app.vue

## Describe the bug

When adding supabase module with [the following instructions](https://github.com/larbish/supabase-module/blob/main/docs/pages/2.setup.md), automatic import of naiveui components don't work anymore. I have to manually import everything.

I wonder if @css-render/vue3-ssr plays well with Nuxt3 ? Do you have an idea what could cause this error ?

## Logs

```
[Vue warn]: Failed to resolve component: n-result
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
[Vue warn]: Failed to resolve component: n-button
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
[Vue warn]: Failed to resolve component: n-space
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
[Vue warn]: Failed to resolve component: n-h2
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
[Vue warn]: Failed to resolve component: n-tooltip
[...]
(node:13) UnhandledPromiseRejectionWarning: TypeError: Invalid value used as weak map key
    at WeakMap.set (<anonymous>)
    at normalizePropsOptions (/home/projects/github-9zcuqu/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:3384:11)
    at createComponentInstance (/home/projects/github-9zcuqu/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6851:23)
    at renderComponentVNode (/home/projects/github-9zcuqu/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:197:22)
    at Module.ssrRenderComponent (/home/projects/github-9zcuqu/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:629:12)
    at _sfc_ssrRender (file:///home/projects/github-9zcuqu/.nuxt/dist/server/server.mjs:7330:31)
    at renderComponentSubTree (/home/projects/github-9zcuqu/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:269:13)
    at renderComponentVNode (/home/projects/github-9zcuqu/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:214:16)
    at Module.ssrRenderComponent (/home/projects/github-9zcuqu/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:629:12)
    at default (file:///home/projects/github-9zcuqu/.nuxt/dist/server/server.mjs:7224:35)
```

**Comment by Baiyuetribe** [comment]
I'm not familiar with supabase, and it's used in nuxt3 with very little information, maybe you can give feedback directly to the author's repository to see. `naive-ui` can be fully automated and introduced on demand thanks to `unplugin-vue-components`. maybe you can refer to this project to implement it
`https://github.com/zulvkr/nuxt3-ts3`
